[wokwi]
version = 1
firmware = "../../firmware/hcp2-bringup/build-wokwi-hp-fallback/flasher_args.json"
elf = "../../firmware/hcp2-bringup/build-wokwi-hp-fallback/hcp2_bringup.elf"

[[chip]]
name = "supramatic4"
binary = "chips/supramatic4.chip.wasm"
