[wokwi]
version = 1
firmware = "../../configs/.esphome/build/supramatic-4-wokwi/.pioenvs/supramatic-4-wokwi/flasher_args.json"
elf = "../../configs/.esphome/build/supramatic-4-wokwi/.pioenvs/supramatic-4-wokwi/firmware.elf"

[[chip]]
name = "supramatic4"
binary = "chips/supramatic4.chip.wasm"
