substitutions:
  name: "supramatic-e2"
  friendly_name: "Garage Door"
  rs485_rx_pin: GPIO16
  rs485_tx_pin: GPIO17

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    board_build.f_cpu: 240000000L

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG
  logs:
    uapbridge_esp: DEBUG
    uapbridge.cover: DEBUG
    uapbridge.binary_sensor: DEBUG

api:
  encryption:
    key: !secret api_key_supramatic_e2

ota:
  - platform: esphome

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9

uart:
  id: uart_bus
  baud_rate: 19200
  rx_pin: ${rs485_rx_pin}
  tx_pin: ${rs485_tx_pin}
  rx_buffer_size: 256

uapbridge_esp:
  id: garage_door_comp
  uart_id: uart_bus
  auto_correction: false
  diagnostic_mode: true
  listen_only: false
  command_timeout: 1200ms
  valid_broadcast_timeout: 10s
  require_fresh_broadcast_for_commands: true
  allow_remote_close: false
  allow_remote_impulse: false
  use_unverified_stop_command: false

cover:
  - platform: uapbridge
    name: "${friendly_name}"
    device_class: garage

switch:
  - platform: uapbridge
    venting_switch:
      name: "${friendly_name} Venting"
      disabled_by_default: true

binary_sensor:
  - platform: status
    name: "${friendly_name} ESPHome Status"
  - platform: uapbridge
    relay_state:
      name: "${friendly_name} Relay State"
    error_state:
      name: "${friendly_name} Error State"
    prewarn_state:
      name: "${friendly_name} Prewarn State"
    got_valid_broadcast:
      name: "${friendly_name} Valid HCP Broadcast"

output:
  - platform: uapbridge
    id: garage_light_output

light:
  - platform: uapbridge
    id: garage_light
    name: "${friendly_name} Light"
    output: garage_light_output

text_sensor:
  - platform: uapbridge
    id: garage_door_state
    name: "${friendly_name} State"
  - platform: ethernet_info
    ip_address:
      name: "${friendly_name} IP Address"
    mac_address:
      name: "${friendly_name} MAC Address"

button:
  - platform: uapbridge
    vent_button:
      name: "${friendly_name} Vent"
      disabled_by_default: true
