api_key_supramatic_e2: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
ota_password_supramatic_e2: "replace-with-a-long-random-ota-password"
api_key_supramatic_4_dev: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
ota_password_supramatic_4_dev: "replace-with-a-long-random-ota-password"
wifi_ssid_supramatic_4_dev: "replace-with-wifi-ssid"
wifi_password_supramatic_4_dev: "replace-with-wifi-password"
api_key_supramatic_4_tester: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
ota_password_supramatic_4_tester: "replace-with-a-long-random-ota-password"
wifi_ssid_supramatic_4_tester: "replace-with-wifi-ssid"
wifi_password_supramatic_4_tester: "replace-with-wifi-password"
proxy_auth_token: "replace-with-a-long-random-token"
