#!/usr/bin/env python3
"""Fetch and normalize the public HCP2 investigation capture corpus."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from urllib.request import urlopen


UPSTREAM_REPO = "Tysonpower/HCPBridgeMqtt_tynet"
UPSTREAM_COMMIT = "e2d8297a868d4dd62781b8b4a305279b787d250c"
INVESTIGATION_URL = (
    "https://raw.githubusercontent.com/"
    f"{UPSTREAM_REPO}/{UPSTREAM_COMMIT}/docs/Investigation.zip"
)
INVESTIGATION_SHA256 = "9130bf43f433d95bf9dc32f1449b854355e5fd5a94c63b0d79b54e556eeb1567"
DEFAULT_OUTPUT_DIR = Path("captures/hcp2")
CAPTURE_RE = re.compile(
    r"^\s*(?P<gap>\d+):(?P<dur>\d+):(?P<len>[0-9A-Fa-f]{4}):\s*(?P<hex>(?:[0-9A-Fa-f]{2}\s*)+)"
)


@dataclass(frozen=True)
class NormalizedFrame:
    t_gap_us: int
    dur_us: int
    raw: str


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download(url: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with urlopen(url, timeout=60) as response:
        data = response.read()
    output_path.write_bytes(data)


def ensure_zip(url: str, expected_sha256: str, output_dir: Path, force: bool) -> Path:
    zip_path = output_dir / "Investigation.zip"
    if force or not zip_path.exists():
        download(url, zip_path)
    actual_sha256 = sha256_file(zip_path)
    if actual_sha256 != expected_sha256:
        if force:
            raise RuntimeError(
                f"Downloaded {zip_path} has SHA-256 {actual_sha256}, expected {expected_sha256}"
            )
        zip_path.unlink(missing_ok=True)
        download(url, zip_path)
        actual_sha256 = sha256_file(zip_path)
        if actual_sha256 != expected_sha256:
            raise RuntimeError(
                f"Downloaded {zip_path} has SHA-256 {actual_sha256}, expected {expected_sha256}"
            )
    return zip_path


def read_dump2(zip_path: Path) -> str:
    with zipfile.ZipFile(zip_path) as outer:
        dump_zip_bytes = outer.read("Investigation/records/dump.zip")
    with zipfile.ZipFile(io.BytesIO(dump_zip_bytes)) as inner:
        return inner.read("dump2.txt").decode("latin1")


def normalize_dump(text: str, strict: bool = False) -> tuple[list[NormalizedFrame], int]:
    frames: list[NormalizedFrame] = []
    skipped = 0
    for line_no, line in enumerate(text.splitlines(), start=1):
        match = CAPTURE_RE.match(line)
        if not match:
            if line.strip():
                if strict:
                    raise ValueError(f"Could not parse dump2.txt line {line_no}: {line!r}")
                skipped += 1
            continue
        raw = "".join(match.group("hex").split()).lower()
        expected_len = int(match.group("len"), 16)
        if len(raw) != expected_len * 2:
            if strict:
                raise ValueError(
                    f"Line {line_no} length field says {expected_len} bytes but raw has {len(raw) // 2}"
                )
            skipped += 1
            continue
        frames.append(
            NormalizedFrame(
                t_gap_us=int(match.group("gap")),
                dur_us=int(match.group("dur")),
                raw=raw,
            )
        )
    return frames, skipped


def write_jsonl(frames: list[NormalizedFrame], output_path: Path) -> None:
    with output_path.open("w", encoding="utf-8") as handle:
        for frame in frames:
            handle.write(
                json.dumps(
                    {"t_gap_us": frame.t_gap_us, "dur_us": frame.dur_us, "raw": frame.raw},
                    separators=(",", ":"),
                )
            )
            handle.write("\n")


def write_readme(output_dir: Path, frame_count: int, skipped_count: int, zip_sha256: str) -> None:
    readme = output_dir / "README.md"
    readme.write_text(
        "\n".join(
            [
                "# HCP2 Reference Corpus",
                "",
                "This directory is generated by `garage-fetch-hcp2-reference` and is ignored by git.",
                "",
                f"- Upstream repository: `{UPSTREAM_REPO}`",
                f"- Pinned commit: `{UPSTREAM_COMMIT}`",
                f"- Source URL: `{INVESTIGATION_URL}`",
                f"- SHA-256: `{zip_sha256}`",
                "- Source path: `Investigation/records/dump.zip` -> `dump2.txt`",
                f"- Normalized frames: `{frame_count}`",
                f"- Skipped malformed/truncated lines: `{skipped_count}`",
                "",
                "Committed fixtures live in `tests/hcp2/vectors/`.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Fetch and normalize the pinned HCP2 investigation corpus")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--url", default=INVESTIGATION_URL)
    parser.add_argument("--sha256", default=INVESTIGATION_SHA256)
    parser.add_argument("--force", action="store_true", help="Re-download even if the zip already exists")
    parser.add_argument("--strict", action="store_true", help="Fail instead of skipping malformed capture lines")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        zip_path = ensure_zip(args.url, args.sha256, args.output_dir, args.force)
        frames, skipped = normalize_dump(read_dump2(zip_path), strict=args.strict)
        output_jsonl = args.output_dir / "dump2.jsonl"
        write_jsonl(frames, output_jsonl)
        write_readme(args.output_dir, len(frames), skipped, sha256_file(zip_path))
    except Exception as exc:
        print(f"garage-fetch-hcp2-reference: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {len(frames)} frames to {output_jsonl} (skipped {skipped} malformed lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
