"""Generate Wokwi custom-chip protocol constants from supramatic_sim."""

from __future__ import annotations

import argparse
from pathlib import Path

from tools.supramatic_sim import protocol, simulator


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "emulation" / "wokwi" / "hcp2_protocol.h"


def c_array(name: str, data: bytes) -> str:
    values = ", ".join(f"0x{byte:02X}" for byte in data)
    return f"static const uint8_t {name}[] = {{ {values} }};\n#define {name}_LEN {len(data)}u\n"


def render() -> str:
    closed = protocol.broadcast_status(protocol.BROADCAST_CLOSED)
    scan_request = protocol.bus_scan_request(protocol.SLAVE_ID)
    poll0 = protocol.status_poll(0, protocol.SLAVE_ID)
    return "".join(
        [
            "/* Generated by garage-generate-wokwi-hcp2-constants. Do not edit by hand. */\n",
            "#pragma once\n\n",
            "#include <stdint.h>\n\n",
            f"#define HCP2_WOKWI_SLAVE_ID 0x{protocol.SLAVE_ID:02X}u\n",
            f"#define HCP2_WOKWI_STEADY_CYCLE_US {simulator.STEADY_CYCLE_US}u\n",
            f"#define HCP2_WOKWI_BROADCAST_TO_POLL_GAP_US {simulator.BROADCAST_TO_POLL_GAP_US}u\n",
            f"#define HCP2_WOKWI_POLL_TO_NEXT_BROADCAST_GAP_US {simulator.POLL_TO_NEXT_BROADCAST_GAP_US}u\n",
            f"#define HCP2_WOKWI_DEFAULT_MISSED_POLL_THRESHOLD {simulator.DEFAULT_MISSED_POLL_THRESHOLD}u\n",
            f"#define HCP2_WOKWI_RESPONSE_TIMEOUT_US {int(simulator.DEFAULT_RESPONSE_TIMEOUT_S * 1_000_000)}u\n\n",
            c_array("HCP2_WOKWI_SCAN_REQUEST", scan_request),
            "\n",
            c_array("HCP2_WOKWI_SCAN_RESPONSE", protocol.SCAN_RESPONSE),
            "\n",
            c_array("HCP2_WOKWI_STATUS_POLL_COUNTER0", poll0),
            "\n",
            c_array("HCP2_WOKWI_BROADCAST_CLOSED", closed),
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != content:
            print(f"{args.output} is stale; run garage-generate-wokwi-hcp2-constants")
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
