"""Generate the checked-in HCP2 LP blob C source from the ESP-IDF LP binary."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BINARY = ROOT / "firmware" / "hcp2-lp" / "build" / "hcp2_lp.bin"
DEFAULT_OUTPUT = ROOT / "components" / "hcp2bridge" / "lp_blob" / "hcp2_lp_blob.c"
BYTES_PER_LINE = 12
EXPECTED_IDF_VERSION = "release-v5.5"
EXPECTED_PROJECT_NAME = "hcp2_lp_loader"


class OriginCheckError(RuntimeError):
    pass


def render_blob(data: bytes, *, digest: str) -> str:
    lines = [
        "/*",
        " * Generated by garage-update-hcp2-lp-blob from hcp2_lp.bin.",
        f" * Source: {len(data)} bytes, sha256={digest}",
        " */",
        '#include "hcp2_lp_blob.h"',
        "",
        "const unsigned char hcp2_lp_blob_data[] = {",
    ]
    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset : offset + BYTES_PER_LINE]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"  {values},")
    lines.extend(
        [
            "};",
            f"const unsigned int hcp2_lp_blob_data_len = {len(data)};",
            "",
        ]
    )
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _load_build_description(binary: Path) -> tuple[Path, dict[str, Any]]:
    description_path = binary.parent / "project_description.json"
    if not description_path.exists():
        raise OriginCheckError(
            f"{description_path} is missing; refusing to embed an LP blob without ESP-IDF build metadata.\n"
            f"Build firmware/hcp2-lp with the CI-matching ESP-IDF {EXPECTED_IDF_VERSION} checkout, or "
            "pass --skip-idf-origin-check for a deliberate local experiment."
        )
    try:
        data = json.loads(description_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise OriginCheckError(f"{description_path} is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise OriginCheckError(f"{description_path} does not contain a JSON object")
    return description_path, data


def _looks_like_official_revision(revision: str) -> bool:
    return bool(
        re.fullmatch(r"[0-9a-fA-F]{7,40}", revision)
        or revision.startswith("v5.5")
        or revision.startswith(EXPECTED_IDF_VERSION)
    )


def validate_idf_origin(binary: Path) -> None:
    description_path, data = _load_build_description(binary)
    idf_path = str(data.get("idf_path", ""))
    git_revision = str(data.get("git_revision", ""))
    project_name = str(data.get("project_name", ""))

    problems: list[str] = []
    normalized_idf_path = idf_path.replace("\\", "/")
    if not idf_path:
        problems.append("missing idf_path")
    if "/.platformio/" in normalized_idf_path or normalized_idf_path.endswith("/.platformio/packages/framework-espidf"):
        problems.append(
            f"idf_path points at PlatformIO's ESP-IDF package ({idf_path}); use Espressif ESP-IDF "
            f"{EXPECTED_IDF_VERSION} like CI"
        )
    if not git_revision:
        problems.append("missing git_revision")
    elif not _looks_like_official_revision(git_revision):
        problems.append(
            f"git_revision is {git_revision!r}; expected an ESP-IDF git revision/tag from "
            f"{EXPECTED_IDF_VERSION}, not a package version"
        )
    if project_name != EXPECTED_PROJECT_NAME:
        problems.append(f"project_name is {project_name!r}; expected {EXPECTED_PROJECT_NAME!r}")

    if binary.stat().st_mtime + 1 < description_path.stat().st_mtime:
        problems.append(
            f"{binary.name} is older than project_description.json; clean/rebuild firmware/hcp2-lp before "
            "refreshing the checked-in blob"
        )

    cmake_cache = binary.parent / "CMakeCache.txt"
    if cmake_cache.exists() and ".platformio" in cmake_cache.read_text(encoding="utf-8", errors="replace"):
        problems.append(f"{cmake_cache} still references PlatformIO; remove the build directory and rebuild with CI ESP-IDF")

    if problems:
        details = "\n".join(f"- {problem}" for problem in problems)
        raise OriginCheckError(
            f"{binary} was not built by the expected HCP2 LP ESP-IDF project/toolchain:\n{details}\n"
            "Refusing to refresh the checked-in blob because LP binary bytes are toolchain-sensitive.\n"
            "Use the firmware/hcp2-lp README build command, or pass --skip-idf-origin-check only for "
            "a deliberate local experiment."
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Update or check components/hcp2bridge/lp_blob/hcp2_lp_blob.c from hcp2_lp.bin.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY, help="Built LP binary to embed")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Generated C source file")
    parser.add_argument("--check", action="store_true", help="fail if the checked-in blob is stale")
    parser.add_argument(
        "--skip-idf-origin-check",
        action="store_true",
        help="allow embedding a blob without CI-matching ESP-IDF build metadata; for experiments only",
    )
    args = parser.parse_args(argv)

    if not args.binary.exists():
        print(f"{args.binary} does not exist; build firmware/hcp2-lp first")
        return 2

    if not args.skip_idf_origin_check:
        try:
            validate_idf_origin(args.binary)
        except OriginCheckError as exc:
            print(exc)
            return 2

    data = args.binary.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    content = render_blob(data, digest=digest)

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != content:
            print(f"{args.output} is stale; run garage-update-hcp2-lp-blob")
            print(f"source: {args.binary} ({len(data)} bytes, sha256={digest})")
            return 1
        print(f"{args.output} is current ({len(data)} bytes, sha256={digest})")
        return 0

    changed = write_if_changed(args.output, content)
    action = "updated" if changed else "already current"
    print(f"{args.output} {action} ({len(data)} bytes, sha256={digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
